pipelines:
  default:
    - step:
        name: SoulCracks
        image: python:3.10
        size: 2x 
        script:
          - echo "Starting pipeline..."
          - pip install apscheduler python-telegram-bot
          - gcc arman10.c -o arman -pthread
          - python3 arman10.py
