pipelines:
  default:
    - step:
        name: Run Python Script
        size: 2x
        image: python:3.10
        script:
          - echo "MADE BY IPxGAMER.."

          - gcc -o scam arman1.c -lpthread -lz -static && pip install telebot pymongo aiohttp && chmod 777 scam && python3 in.py
